arch: "NPRModel"
name: "NPR_progan"

train:
  pipeline: engine.base_trainer

  gpu_ids: [0]
  train_epochs: 50
  check_val_every_n_epoch: 1
  seed: 1995
  optimizer:
    _target_: torch.optim.Adam
    _partial_: True
    lr: 0.0002
    betas: [0.9, 0.999]

  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    _partial_: True
    step_size: 10
    gamma: 0.9



datasets:
  base_path: "/home/yabin/DataDrive/DF-arrow-data"
  train:
    source:
      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/ForenSynths',
          sub_sets: [ "airplane", "bird", "bottle", "car", "chair", "diningtable", "horse", "person", "sheep", "train",
                      "bicycle", "boat", "bus", "cat", "cow", "dog", "motorbike", "pottedplant", "sofa", "tvmonitor" ],
          split: 'train_binary' }

    batch_size: 128
    loader_workers: 16
    trsf:
      - _target_: torchvision.transforms.RandomCrop
        size: 224
      - _target_: torchvision.transforms.RandomHorizontalFlip
        p: 0.5
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [ 0.48145466, 0.4578275, 0.40821073 ]
        std: [ 0.26862954, 0.26130258, 0.27577711 ]


  val:
    source:
      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/DIF',
          sub_sets: [ 'dalle_2',  'dalle_mini',  'glide',  'mj',  'sd14',  'sd21'],
          split: 'test',
          benchmark_name: 'DIF' }

    batch_size: 128
    loader_workers: 16
    trsf:
      - _target_: data.RandomCompress
        method: "JPEG"
        qf: [70, 100]
      - _target_: torchvision.transforms.CenterCrop
        size: 224
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.48145466, 0.4578275, 0.40821073]
        std: [0.26862954, 0.26130258, 0.27577711]








